name: lagrange
version: 0.0.1
author: Axel Christ
description: Package for lagrange interpolation
homepage: https://github.com/Adracus/lagrange
documentation: https://github.com/Adracus/lagrange
dev_dependencies:
  unittest: any
